// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIRNQGcUkRolUw0q3NIzpmDKRHQk7IzM',
    appId: '1:718933187895:web:952a4fc85271f6d8a88eb2',
    messagingSenderId: '718933187895',
    projectId: 'act16-f2a55',
    authDomain: 'act16-f2a55.firebaseapp.com',
    storageBucket: 'act16-f2a55.firebasestorage.app',
    measurementId: 'G-MTSW12S0VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFXZxedmefyjYwyC0M0skh-aSk1fLBsPI',
    appId: '1:718933187895:android:0f0cb77581772747a88eb2',
    messagingSenderId: '718933187895',
    projectId: 'act16-f2a55',
    storageBucket: 'act16-f2a55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj01c1_R3KtMlhLLqQz7d1i2wQ5dSW-yg',
    appId: '1:718933187895:ios:9079947be21574e4a88eb2',
    messagingSenderId: '718933187895',
    projectId: 'act16-f2a55',
    storageBucket: 'act16-f2a55.firebasestorage.app',
    iosBundleId: 'com.example.act16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj01c1_R3KtMlhLLqQz7d1i2wQ5dSW-yg',
    appId: '1:718933187895:ios:9079947be21574e4a88eb2',
    messagingSenderId: '718933187895',
    projectId: 'act16-f2a55',
    storageBucket: 'act16-f2a55.firebasestorage.app',
    iosBundleId: 'com.example.act16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIRNQGcUkRolUw0q3NIzpmDKRHQk7IzM',
    appId: '1:718933187895:web:f0ee0d2455e49c2da88eb2',
    messagingSenderId: '718933187895',
    projectId: 'act16-f2a55',
    authDomain: 'act16-f2a55.firebaseapp.com',
    storageBucket: 'act16-f2a55.firebasestorage.app',
    measurementId: 'G-R2W096T8QC',
  );
}
